A	backend/src/main/java/vn/edu/phenikaa/courseregistration/controller/AuthController.java
A	backend/src/main/java/vn/edu/phenikaa/courseregistration/controller/StudentController.java
A	backend/src/main/java/vn/edu/phenikaa/courseregistration/dto/request/LoginRequest.java
A	backend/src/main/java/vn/edu/phenikaa/courseregistration/dto/response/StudentResponse.java
A	backend/src/main/java/vn/edu/phenikaa/courseregistration/exception/StudentNotFoundException.java
A	backend/src/main/java/vn/edu/phenikaa/courseregistration/mapper/StudentMapper.java
M	backend/src/main/java/vn/edu/phenikaa/courseregistration/model/Student.java
D	backend/src/main/java/vn/edu/phenikaa/courseregistration/repository/JsonFileRepository.java
A	backend/src/main/java/vn/edu/phenikaa/courseregistration/repository/StudentRepository.java
A	backend/src/main/java/vn/edu/phenikaa/courseregistration/repository/file/JsonStudentRepository.java
A	backend/src/main/java/vn/edu/phenikaa/courseregistration/service/AuthService.java
A	backend/src/main/java/vn/edu/phenikaa/courseregistration/service/StudentService.java
M	frontend/src/app/App.tsx
M	frontend/src/features/auth/api/authApi.ts
M	frontend/src/features/auth/pages/LoginPage.tsx
M	frontend/src/features/profile/api/profileApi.ts
M	frontend/src/features/profile/pages/ProfilePage.tsx
M	frontend/src/features/profile/types/profile.types.ts
M	frontend/src/shared/constants/apiEndpoints.ts
